# Generated by Django 2.1.5 on 2019-05-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_review',
            old_name='user',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='movie_review',
            name='metadata',
        ),
        migrations.AddField(
            model_name='movie_review',
            name='reviewrating',
            field=models.IntegerField(default=False),
        ),
    ]
