# Generated by Django 2.1.5 on 2019-05-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20190520_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_review',
            name='movietype',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='movie_review',
            name='poster',
            field=models.URLField(default=False),
        ),
        migrations.AddField(
            model_name='movie_review',
            name='title',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='movie_review',
            name='year',
            field=models.IntegerField(default=False),
        ),
    ]
