# Generated by Django 2.1.5 on 2019-05-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_movie_review_imdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_review',
            name='reviewrating',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
