# Generated by Django 2.1.5 on 2019-05-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_auto_20190520_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_review',
            name='reviewcategory',
            field=models.TextField(default=False),
        ),
    ]
