# Generated by Django 2.1.5 on 2019-05-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_movie_review_reviewcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_review',
            name='reviewcategory',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
